### ISSUE TITLE
Having trouble connecting to servers when downloading a game.

### ISSUE THREAD

**Issue by censlin** [desura/Desurium#287]
Two error messages:
“There was an error during the MCF download process and it has been stopped.

All server connections failed.

Please check you are connected to the internet and try again or check console for more info. [59.0]”

and

“There was an error during the validation process and it has been stopped.

Did not get any data from mcf server. [18.0]”

This problem seems to specific to Desurium; Desura works fine.

**Comment by censlin** [comment]
I also have a third error that seems to be a slightly different issue indirectly caused by this:
“There was an error during the validation process and it has been stopped.

Couldn’t open the file [/home/someuser/.desura/games/12034/bf842_m1.mcf”

It seems that Desurium somehow turned this file into a directory. Deleting it fixes the problem.

**Comment by censlin** [comment]
Some background: My internet connection tends to be slightly unstable. It's not that I completely lose the connection, but I have some packet loss from time to time. Some of the less sturdy programs (like rsync, git, etc.) tends to have some connection problems.

**Comment by censlin** [comment]
The problem isn't always immediate: some games will download a few dozen megabytes before the problem occurs, while others will fail immediately. I get the idea that this happens when Desurium tries to connect to specific servers.

**Comment by ssokolow** [comment]
Huh. I was getting that "Couldn't open this file" message for one of my games. I deleted my old Desurium folder (to save space) as part of losing interest in games too closed-source to have a port to my new [OpenPandora](http://openpandora.org/), but I'll have to see if it works now that I've done so.

(I say "too closed-source" because the developers of various games like VVVVVV and Uplink have allowed volunteers access to their source for porting purposes when they asked nicely.)

**Comment by ssokolow** [comment]
Looks like I'm having the same problem. After blowing away `~/.desura` and starting from scratch, [Super Office Stress](http://www.desura.com/games/super-office-stress) still fails to install and it's giving me the same errors you quoted.

**Comment by makson96** [comment]
Same error here on OilRush. I thought it was somehow connected to bad game update, but it might be Desurium fault as well.

“There was an error during the MCF download process and it has been stopped.

All server connections failed.

Please check you are connected to the internet and try again or check console for more info. [59.0]”

**Comment by lodle** [comment]
Desura had some server issues last night causing all downloads to fail. should befixed now.

**Comment by makson96** [comment]
Well, I am still unable to download any game. Just like yesterday MCF download error.

**Comment by censlin** [comment]
Same here; still getting my first error.

**Comment by karolherbst** [comment]
I have some errors, too

**Comment by lodle** [comment]
Post the errors please

**Comment by makson96** [comment]
This is my whole Desura Console output, when I try to download a game:

10:50   MCFCore Logging Started.
10:50   WebCore Logging Started.
10:50   UserCore Logging Started.
10:50   --------------------------------------------------
10:50   Desura Version      : 1.0.0.0
10:50   MCFCore Version     : 0.0.0.1
10:50   UICore Version      : 0.0.0.1
10:50   UserCore Version    : 0.0.0.1
10:50   WebCore Version     : 0.0.0.1
10:50   --------------------------------------------------
10:50   Logging has started
10:50  
10:50   DS: Version: 0.0.0.1
10:50   Failed to save item to db: database is locked
10:50   Failed to save item to db: database is locked
10:50   Failed to save item to db: database is locked
10:51   Failed crc check. Writen to log file [/home/makson/.desura/crc/crc_log.txt], block saved to file [/home/makson/.desura/crc/65558380806176/block_35_1345020669.bin].
10:51   Mcf download thread errored out. Id: 2, Error: Crc of the download chunk didnt match what was expected [0]
10:51   Failed crc check. Writen to log file [/home/makson/.desura/crc/crc_log.txt], block saved to file [/home/makson/.desura/crc/65558380806176/block_35_1345020671.bin].
10:51   Mcf download thread errored out. Id: 2, Error: Crc of the download chunk didnt match what was expected [0]
10:51   Failed crc check. Writen to log file [/home/makson/.desura/crc/crc_log.txt], block saved to file [/home/makson/.desura/crc/65558380806176/block_35_1345020673.bin].
10:51   Mcf download thread errored out. Id: 2, Error: Crc of the download chunk didnt match what was expected [0]
10:51   Failed crc check. Writen to log file [/home/makson/.desura/crc/crc_log.txt], block saved to file [/home/makson/.desura/crc/65558380806176/block_35_1345020675.bin].
10:51   Mcf download thread errored out. Id: 2, Error: Crc of the download chunk didnt match what was expected [0]
10:51   Failed crc check. Writen to log file [/home/makson/.desura/crc/crc_log.txt], block saved to file [/home/makson/.desura/crc/65558380806176/block_35_1345020678.bin].
10:51   Mcf download thread errored out. Id: 2, Error: Crc of the download chunk didnt match what was expected [0]
10:51   Failed crc check. Writen to log file [/home/makson/.desura/crc/crc_log.txt], block saved to file [/home/makson/.desura/crc/65558380806176/block_35_1345020679.bin].
10:51   Mcf download thread errored out. Id: 2, Error: Crc of the download chunk didnt match what was expected [0]
10:51   WebGet: 2 Error: No more download servers to use. [60.0].
10:51   Error in MCF download: All server connections failed. 
10:51  
10:51   Please check you are connected to the internet
10:51   and try again or check console for more info. [59.0]
10:51   There was an error during the MCF download process and it has been stopped.: All server connections failed. 
10:51  
10:51   Please check you are connected to the internet
10:51   and try again or check console for more info. [59.0]

**Comment by lodle** [comment]
Getting a fix for this on the weekend.

**Comment by TheSiege** [comment]
I would like to post my output
It is interesting how the all server refused connection error is early while the download collapses when the download is almost complete:
10:49   MCFCore Logging Started.
10:49   WebCore Logging Started.
10:49   UserCore Logging Started.
10:49   --------------------------------------------------
10:49   Desura Version      : 1.0.0.0
10:49   MCFCore Version     : 0.0.0.1
10:49   UICore Version      : 0.0.0.1
10:49   UserCore Version    : 0.0.0.1
10:49   WebCore Version     : 0.0.0.1
10:49   --------------------------------------------------
10:49   Logging has started
10:49  
10:49   Loaded Language file: german
10:49   Failed to generate useragent string.
10:49   DS: Version: 0.0.0.1
10:49   Failed to generate useragent string.
10:49   Failed to save item to db: database is locked
10:49   Failed to save item to db: database is locked
10:49   Failed to save item to db: database is locked
10:49   Error in MCF validate: Couldn't open the file [/home/anagromataf/.desura/games/15264/b994_m18.mcf] in mode 2 [9.0]
10:49   Es gab einen Fehler beim überprüfen.: Couldn't open the file [/home/anagromataf/.desura/games/15264/b994_m18.mcf] in mode 2 [9.0]
10:51   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345539094.bin].
10:51   Mcf download thread errored out. Id: 0, Error: Crc of the download chunk didnt match what was expected [0]
10:51   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345539101.bin].
10:51   Mcf download thread errored out. Id: 0, Error: Crc of the download chunk didnt match what was expected [0]
10:51   WebGet: 0 Error: No more download servers to use. [60.0].
11:10   Mcf Server error: Timeout was reached (ftp://us4.dl.desura.com:62003/mcf) [FTP response timeout] [58.28] [mcf://us4.dl.desura.com:62003]
11:10   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345540238.bin].
11:10   Mcf download thread errored out. Id: 2, Error: Crc of the download chunk didnt match what was expected [0]
11:10   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345540241.bin].
11:10   Mcf download thread errored out. Id: 2, Error: Crc of the download chunk didnt match what was expected [0]
11:10   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345540243.bin].
11:10   Mcf download thread errored out. Id: 2, Error: Crc of the download chunk didnt match what was expected [0]
11:10   WebGet: 2 Error: No more download servers to use. [60.0].
11:13   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345540396.bin].
11:13   Mcf download thread errored out. Id: 1, Error: Crc of the download chunk didnt match what was expected [0]
11:13   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345540399.bin].
11:13   Mcf download thread errored out. Id: 1, Error: Crc of the download chunk didnt match what was expected [0]
11:13   Mcf Server error: FTP: unknown PASV reply (ftp://us5.dl.desura.com:62003/mcf) [Bad PASV/EPSV response: 451] [58.13] [mcf://us5.dl.desura.com:62003]
11:13   Mcf download thread errored out. Id: 1, Error: FTP: unknown PASV reply (ftp://us5.dl.desura.com:62003/mcf) [Bad PASV/EPSV response: 451] [13]
11:13   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345540402.bin].
11:13   Mcf download thread errored out. Id: 1, Error: Crc of the download chunk didnt match what was expected [0]
11:13   WebGet: 1 Error: No more download servers to use. [60.0].
11:13   Error in MCF download: All server connections failed. 
11:13  
11:13   Please check you are connected to the internet
11:13   and try again or check console for more info. [59.0]
11:13   Es trat ein fehler während des Downloads der MCF auf.: All server connections failed. 
11:13  
11:13   Please check you are connected to the internet
11:13   and try again or check console for more info. [59.0]
11:46   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345542383.bin].
11:46   Mcf download thread errored out. Id: 0, Error: Crc of the download chunk didnt match what was expected [0]
11:46   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345542384.bin].
11:46   Mcf download thread errored out. Id: 0, Error: Crc of the download chunk didnt match what was expected [0]
11:46   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345542387.bin].
11:46   Mcf download thread errored out. Id: 0, Error: Crc of the download chunk didnt match what was expected [0]
11:46   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345542388.bin].
11:46   Mcf download thread errored out. Id: 0, Error: Crc of the download chunk didnt match what was expected [0]
11:46   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345542391.bin].
11:46   Mcf download thread errored out. Id: 0, Error: Crc of the download chunk didnt match what was expected [0]
11:46   Failed crc check. Writen to log file [/home/anagromataf/.desura/crc/crc_log.txt], block saved to file [/home/anagromataf/.desura/crc/65558380806176/block_35_1345542392.bin].
11:46   Mcf download thread errored out. Id: 0, Error: Crc of the download chunk didnt match what was expected [0]
11:46   WebGet: 0 Error: No more download servers to use. [60.0].
11:46   Error in MCF download: All server connections failed. 
11:46  
11:46   Please check you are connected to the internet
11:46   and try again or check console for more info. [59.0]
11:46   Es trat ein fehler während des Downloads der MCF auf.: All server connections failed. 
11:46  
11:46   Please check you are connected to the internet
11:46   and try again or check console for more info. [59.0]

**Comment by lodle** [comment]
pull latest changes. should fix it.

**Comment by TheSiege** [comment]
I regret to inform you that the latest changes are 19 days ago and I rebuild desurium just yesterday and do have this problem

**Comment by makson96** [comment]
For me most of the games download just fine to date. But unfortunately for OilRush I still get the same error, which I previously quoted.

**Comment by TheSiege** [comment]
yeah oil rush for me too; I wonder if the error could be on the server

**Comment by lodle** [comment]
my commit on the weekend didnt make it. ill find out what happened to it.

**Comment by lodle** [comment]
https://github.com/lodle/Desurium/commit/64b4fa7e66b3ee63120d83067378a6e17a1a1937

**Comment by FrankyB** [comment]
Still no luck with oil rush

cat crc_log.txt 
Crc of block didnt match expected.
File: launcher_x64.sh
WebOffset: 35
FileOffset: 721194892
Expected Crc: 481019868
Crc: 2629633680
Out File: /home/logge_13/.desura/crc/65558380806176/block_721194892_1345620800.bin
Size: 251
Mcf: 15264
Build: 18
Branch: 994
Provider: Desura #6

Crc of block didnt match expected.
File: launcher_x64.sh
WebOffset: 35
FileOffset: 721194892
Expected Crc: 481019868
Crc: 2629633680
Out File: /home/logge_13/.desura/crc/65558380806176/block_721194892_1345620802.bin
Size: 251
Mcf: 15264
Build: 18
Branch: 994
Provider: Desura #6

Crc of block didnt match expected.
File: launcher_x64.sh
WebOffset: 35
FileOffset: 721194892
Expected Crc: 481019868
Crc: 2629633680
Out File: /home/logge_13/.desura/crc/65558380806176/block_721194892_1345620804.bin
Size: 251
Mcf: 15264
Build: 18
Branch: 994
Provider: Desura #5

**Comment by karolherbst** [comment]
I think this file (launcher_x64.sh) is broken on the server. I think it can be only fixed by desura

**Comment by karolherbst** [comment]
Also I checked an old commit (30cc60ac4cfd2217dc430a3ca3ab87ef4d1c32ff) and this error also happens there, so it has to be a server issue

**Comment by FrankyB** [comment]
@karolherbst: you might be right, oil rush is not updating on desura as well

**Comment by karolherbst** [comment]
could someone create a bug report to the official desura guys with log files and stuff? I can't do that now

**Comment by FrankyB** [comment]
I have no idea where their bugtracker is, so I added it to this thread

http://www.desura.com/groups/desura/forum/thread/installation-of-oil-rush-dlc-fails/#766050

**Comment by s--d** [comment]
Today I saw a similar looking validation error.  I've copied out the error console text, but feel it's silly to paste yet more logs unless they'll actually help.  Will there be an approved build that my Desura install will update to, or are we relegated to building our own up-to-date Desura clients?

Thanks!

**Comment by karolherbst** [comment]
this errors occurs only for a few files. This must be a server related issue with some CRC missmatches. I will close this issue now.

Errors, which are CRC related should be posted on desura boards or tech support, not here.
