### ISSUE TITLE
Release Information 0.8

### ISSUE THREAD

**Issue by karolherbst** [desura/Desurium#537]
latest release: 0.8.0_rc10

[changelog](https://github.com/lodle/Desurium/blob/0.8/CHANGELOG)

**Comment by karolherbst** [comment]
I want to create a new RC this weekend. Any objections about that?

**Comment by Jookia** [comment]
None here. What happened to rc2-5?

**Comment by karolherbst** [comment]
only bugs, that happend after open sourcing I think

**Comment by karolherbst** [comment]
#121 was fixed in rc2. Maybe I should clean up this file a bit and add some missing stuff

**Comment by Jookia** [comment]
One suggestion is that you finish the Windows stuff up before 0.8 is released. I have no idea how hard that is, but it'd make Desurium not a regression. That and we should probably get licensing worked out. Can somebody get a GitHub account for Desura stuff?

**Comment by karolherbst** [comment]
I don't want to cherry-pick the windows stuff on the 0.8 branch. I would prefer to keep 0.8 stable and just create a new 0.9 branch.

**Comment by karolherbst** [comment]
do you mean a github desura organisation account?

**Comment by Jookia** [comment]
I mean having somebody from Desura on GitHub. I don't really care which way.

**Comment by karolherbst** [comment]
ahh okay

**Comment by karolherbst** [comment]
I cleaned the changelog file and added missing stuff.

**Comment by karolherbst** [comment]
I think we should do another RC before a final release (even after the license stuff got sorted out).

I want to merge #541 for this.

Also we should either look deeper into #539 or just merge it. For me it doesn't make any sense, why replacing copy_file with copy fix this (for me this looks like an arch bug, but I will try to reproduce this).

**Comment by karolherbst** [comment]
I have to correct my statement: the boost problems we have are both: a distibution bug and a little change in boost.

in the arch boost package the static library for test execution is missing, but boost-1.53 changed the variable name for enforcinf scoped enum emulation.

I've create a patch to fix that: https://github.com/karolherbst/Desurium/commit/684b11849e0ae59d115f096e0fc940e6a7de6f18

**Comment by karolherbst** [comment]
I am sure it is fair enough to merge #542 and #541 and create a new rc on Friday maybe.

**Comment by prettyv** [comment]
There seems to have been an error when tagging rc10 - it only includes fixes up to Mar 29, which I'm pretty sure was not the intention. So most notably it will still not compile on Arch due to the missing Boost fixes.
And btw, could you use annotated tags so 'git describe' can be more useful? (e.g. for use in the pkgver()-function for the new makepkg)

**Comment by karolherbst** [comment]
thanks, I fixed this

**Comment by prettyv** [comment]
It is still missing some commits from master, e.g. https://github.com/lodle/Desurium/commit/9e7a47250cee4152fad7ec7a5ef85eaa85c989c6, which keeps me from compiling with wxWidgets 2.9.4 (I know it's still unstable, and it works on master, so for the purpose of playing around that would suffice I guess). Just not sure whether that slipped through or is intentional...

**Comment by karolherbst** [comment]
no, it does not work with wxWidgets 2.9.4

We have crashes while updating and installing games, also the GUI seems to be a bit unstable at all. We want to wait until 2.9.5 and see how things changed. Maybe we stay at 2.9.3 until 2.10 (or 3) arrives.

For some reasons, we did not remove this compile check from 0.8. 0.8 shall be a stable branch, where we don't cherry-pick stuff, which could harm the client without benefits.

If you want to try out things, you can use the master branch.

**Comment by karolherbst** [comment]
@lodle @oz-linden what are your thoughts of having a 0.8 release? there is the idea of skipping it and move forwared with the 0.9 release, because it does add windows support. That would mean, the we have to stabilize the windows build, add some important features and mhh I think we will be ready for a release in 3 months.

**Comment by karolherbst** [comment]
If we decide to go on with 0.9 I would create another 0.8 rc (with the latest changes) and declare it as the last release of 0.8.

**Comment by makson96** [comment]
Hi,
As it goes for me the timing is great. Ubuntu 13.10 is just around the corner and I can include support for it in desurium-stable ppa with this new rc:
https://launchpad.net/~makson96/+archive/desurium-stable
As so much work is now in 0.9 branch I feel fine with this rc being final 0.8 version. But one last think I would like to include in it, is support for system curl, which would be nice for my ppa.

**Comment by karolherbst** [comment]
you are free to apply patches in your build. I just have problems with verifying your fix.

**Comment by karolherbst** [comment]
Maybe it will be the best if you add this to your ppa and if nobody complains about errors with system curl we can close this bug

**Comment by makson96** [comment]
Hmm, OK. I will test it one more time today and upload new builds with it to Desurium Weekly PPA. We will see if somebody complains about it...

**Comment by karolherbst** [comment]
Yeah, but the error did not occur in my kvm ubuntu at all. I could test it on another laptop later this day

**Comment by lodle** [comment]
We are looking at releasing a windows build to qa this week and start testing on it (0.9 but from my branch atm). Hope it wont take 3 months though

**Comment by karolherbst** [comment]
okay, I took some of the github issues into account, that's why 3 months.

**Comment by lodle** [comment]
i will prob move some issues to 1.0

**Comment by karolherbst** [comment]
okay

**Comment by karolherbst** [comment]
I've moved some not so important issues into the 0.9 milestone.

**Comment by lodle** [comment]
Ive added a 0.91 milestone for things we wont fix (i.e. linux bugs) in the initial release

**Comment by karolherbst** [comment]
okay, fine for me. I am planning a last 0.8-rc just because we have some bugfixes on the 0.8 branch, which are pretty safe.
