### ISSUE TITLE
CD-Key/Gift activate button stays greyed out when pasted into

### ISSUE THREAD

**Issue by TheSiege** [desura/Desurium#635]
the Activate button stays greyed out when a Key is pasted into CD-Key/Gift until a button on the keyboard is pressed; this is annoying nothing major

Picture shows an example text

![desura key](https://f.cloud.github.com/assets/1504579/1263268/11051e46-2c4c-11e3-8dd0-2b9d5b2dc6b3.jpeg)

**Comment by lodle** [comment]
Callum said this is fixed in latest version on github. Will retest next release

**Comment by TheSiege** [comment]
this bug is still present with latest master on my gentoo/linux machine, however it seems this bug is not on windows

**Comment by lodle** [comment]
Need some one to test on linux

**Comment by Jookia** [comment]
I can confirm this.
